import pygame

# Константы
SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
# Цвета
BLUE = (135, 206, 250)  # Синий фон по умолчанию
BLACK = (0, 0, 0)  # Цвет текста и кнопок
WHITE = (255, 255, 255)  # Цвет текста кнопок
CRANE_COLOR = (255, 165, 0)  # Оранжевый цвет для крана

LADDER_HEIGHT = SCREEN_HEIGHT
RUNG_SPACING = 40  # Расстояние между перекладинами
BIRD_SIZE = 100
CRANE_SIZE = 150

screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
clock = pygame.time.Clock()
crane = pygame.Rect(SCREEN_WIDTH // 2 - CRANE_SIZE // 2, -CRANE_SIZE, CRANE_SIZE, CRANE_SIZE)

SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080
FPS = 60
CHAR_SPEED = 300
ANIMATION_SPEED = 10
BG_ANIMATION_SPEED = 100
LADDER_WIDTH = 20

# Границы камеры
CAMERA_LEFT_BORDER = SCREEN_WIDTH // 3
CAMERA_RIGHT_BORDER = 2 * SCREEN_WIDTH // 3
CAMERA_TOP_BORDER = SCREEN_HEIGHT // 3
CAMERA_BOTTOM_BORDER = 2 * SCREEN_HEIGHT // 3

# Границы уровня
LEVEL_MIN_X = 672
LEVEL_MAX_X = 1242
LEVEL_MIN_Y = 0
LEVEL_MAX_Y = 15744

# Состояния игры
STATE_NORMAL = 0
STATE_CAPTURED = 1
STATE_CARRYING = 2
STATE_DEATH = 3

# Настройки врагов (базовые значения)
BASE_EAGLE_SPAWN_RANGE = (1.5, 3.5)
BASE_EAGLE_SPEED_RANGE = (300, 1500)
BASE_MAX_EAGLES = 2

BASE_HELICOPTER_SPAWN_RANGE = (2.0, 4.0)
BASE_HELICOPTER_SPEED_RANGE = (400, 1200)
BASE_HELICOPTER_SPAWN_Y_RANGE = (5000, 11760)
BASE_MAX_HELICOPTERS = 2

BASE_UFO_SPAWN_RANGE = (2.5, 5.0)
BASE_UFO_SPEED_RANGE = (350, 1000)
BASE_MAX_UFOS = 2
BASE_UFO_WARNING_TIME = 0.5
BASE_UFO_DEATH_LIGHT_TIME = 0.5
BASE_UFO_LASER_WIDTH = 5
BASE_UFO_LASER_LENGTH = 1000
BASE_UFO_CHAOS_FACTOR = 1.5
BASE_UFO_HORIZONTAL_RANGE = (500, 1500)

BASE_BRICK_SPAWN_RANGE = (5, 10)
BASE_BRICK_SPEED_RANGE = (200, 300)
BASE_MAX_BRICKS = 2

# Уровни сложности
DIFFICULTY_EASY = 0
DIFFICULTY_NORMAL = 1
DIFFICULTY_HARD = 2
